parameters:
#    vad_site.example.class: Vad\SiteBundle\Example

services:
#    vad_site.example:
#        class: %vad_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
